# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57dad2dda78e4f5c2048b48ecd6e92d4130ccd7864b40c0a1c12267d2926937a27e3223f23afe8dc9b70fdfc53f224d2ee58b7462fca6240ee875c35f441947e

test:
  secret_key_base: c81b6e86b719fb3e8a3d6f1cf2d0e5964906cc36ae6a26983d1929630702afb2c14aeca770acb86f4850cf977f32771e8768ea4b873c81627bf3fb4afb246ffd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
